// Code generated by go generate; DO NOT EDIT.
package database

var SqlMap = map[string]string{
	"schema_version_1": `create table schema_version (
    version text not null
);

create table room_group_map ( 
    id integer not null generated always as identity,
    ldap_group text unique,
    matrix_room text unique
);

`,
}
var SqlMapChecksums = map[string]string{
	"schema_version_1": "a7e1b9241755cfff4263d14b75c1a8df801d03cb223874ed13546107a3f0d718",
}
